#!/bin/csh
#
# Open bounds file and read in variables
#
set bds=`cat bound.gmt`
#
set bounds = "-R${bds[1]}/${bds[2]}/${bds[3]}/${bds[4]}"
set proj = "-Jl135:00/-40:00/-5:0/-22:30/0.3"
set psfile = "plotgmt.ps"
#
gmt xyz2grd grid2dv.z -Ggrid2dv.grd -I${bds[5]}+/${bds[6]}+ -ZLB $bounds
#gmt xyz2grd grid2dt.z -Ggrid2dt.grd -I${bds[7]}/${bds[8]} -ZLB $bounds
gmt grdimage grid2dv.grd $bounds $proj -Cvelgradabs.cpt -K -P >! $psfile
gmt psscale -Cvelgradabs.cpt -Ba0.2f0.2:Velocity:/:km/s: -D7.3/14.3/12.00/0.4h -O -K -P >> $psfile
#gmt grdcontour grid2dt.grd $bounds $proj -W3 -C20.0 -O -K -P >> $psfile
#gmt psxy rays.dat $bounds $proj -W0.5 -O -K -P >> $psfile
gmt psxy receivers.dat $bounds $proj -: -St0.10 -G50/50/200 -W3 -O -K -P >> $psfile
gmt psxy sources.dat $bounds $proj -: -St0.10 -G50/50/50 -W3 -O -K -P >> $psfile
gmt pscoast $bounds $proj -Ia -W1 -A2 -Ba10f5/a10f5 -Df -O -P >> $psfile
gmt psconvert $psfile -A -Tf
